# Generated by Django 5.2.7 on 2025-10-16 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='base_portion',
            field=models.CharField(default='1 порция', max_length=100, verbose_name='Базовая порция'),
        ),
    ]
