# Generated by Django 5.2.7 on 2025-10-30 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition_app', '0003_alter_userprofile_options_telegramuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата плана')),
                ('meal_type', models.CharField(choices=[('breakfast', 'Завтрак'), ('lunch', 'Обед'), ('snack', 'Перекус'), ('dinner', 'Ужин')], max_length=20, verbose_name='Прием пищи')),
                ('portion_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=4, verbose_name='Множитель порции')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutrition_app.recipe', verbose_name='Рецепт')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'План питания пользователя',
                'verbose_name_plural': 'Планы питания пользователей',
                'ordering': ['date', 'meal_type'],
                'unique_together': {('user', 'date', 'meal_type')},
            },
        ),
    ]
