# Generated by Django 5.2.7 on 2025-11-15 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition_app', '0006_telegramlinktoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usernotificationsettings',
            name='send_evening_reminder',
        ),
        migrations.RemoveField(
            model_name='usernotificationsettings',
            name='send_morning_reminder',
        ),
        migrations.AddField(
            model_name='usernotificationsettings',
            name='send_breakfast_reminder',
            field=models.BooleanField(default=True, verbose_name='Уведомления о завтраке'),
        ),
        migrations.AddField(
            model_name='usernotificationsettings',
            name='send_dinner_reminder',
            field=models.BooleanField(default=True, verbose_name='Уведомления об ужине'),
        ),
        migrations.AddField(
            model_name='usernotificationsettings',
            name='send_lunch_reminder',
            field=models.BooleanField(default=True, verbose_name='Уведомления об обеде'),
        ),
        migrations.AddField(
            model_name='usernotificationsettings',
            name='send_snack_reminder',
            field=models.BooleanField(default=True, verbose_name='Уведомления о перекусе'),
        ),
    ]
